# -*- coding: utf-8 -*-
"""CV PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cXPyfniY2-jc65KVcNojOwKtFUkhBaqf
"""

import numpy as np, cv2, os, base64
from skimage.morphology import skeletonize
from IPython.display import HTML

print("NumPy:", np.__version__)     # should be 1.26.4
print("OpenCV:", cv2.__version__)   # should be 4.9.0.80

# Create folders
os.makedirs('/content/videos', exist_ok=True)
os.makedirs('/content/output', exist_ok=True)
print("Setup OK.")

from google.colab import files
import os, shutil

# Create a folder to store your videos
os.makedirs('/content/videos', exist_ok=True)

print("👉 Choose your 3 videos when the file picker appears (one by one)")
uploaded = files.upload()  # Select all three videos you just shared

# Move them into the /content/videos directory
for name in uploaded.keys():
    src = f'/content/{name}'
    dst = f'/content/videos/{name}'
    if os.path.exists(src):
        shutil.move(src, dst)

print("\n✅ Upload complete. Saved videos:")
print(os.listdir('/content/videos'))

import cv2, base64
from IPython.display import HTML

def show_video(path, width=640):
    """Helper function to display video directly in notebook"""
    mp4 = open(path,'rb').read()
    data_url = "data:video/mp4;base64," + base64.b64encode(mp4).decode()
    return HTML(f"""<video width="{width}" controls>
                    <source src="{data_url}" type="video/mp4">
                    </video>""")

# Test 1: Play your classroom video
show_video("/content/videos/College_Students_Candid_Classroom_Video.mp4")

# Test 2: Hallway video
show_video("/content/videos/Generating_School_Hallway_Video.mp4")

# Test 3: Driving video
show_video("/content/videos/Driving_and_Walking_Video_Generation.mp4")

import cv2, base64, os
from IPython.display import HTML

def open_video(path):
    cap = cv2.VideoCapture(path)
    assert cap.isOpened(), f"❌ Cannot open: {path}"
    w   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    n   = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    return cap, w, h, fps, n

def video_writer(out_path, w, h, fps=30.0):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    return cv2.VideoWriter(out_path, fourcc, fps, (w, h))

def show_video(path, width=640):
    mp4 = open(path,'rb').read()
    data_url = "data:video/mp4;base64," + base64.b64encode(mp4).decode()
    return HTML(f"""<video width="{width}" controls>
                      <source src="{data_url}" type="video/mp4">
                    </video>""")

in_path = "/content/videos/Generating_School_Hallway_Video.mp4"  # change if you want
cap, W, H, FPS, N = open_video(in_path)
print(f"Opened: {in_path} | {W}x{H} | {FPS:.1f} fps | {N} frames")

out_path = "/content/output/smoke_test.mp4"
writer = video_writer(out_path, W, H, FPS)

max_frames = int(min(N, FPS*5))  # ~5 seconds
i = 0
while i < max_frames:
    ok, frame = cap.read()
    if not ok: break
    writer.write(frame)
    i += 1

cap.release()
writer.release()
print(f"✅ Wrote {i} frames to {out_path}")

show_video(out_path)

from IPython.display import Video
Video("/content/output/smoke_test.mp4", embed=True, width=640)

# Re-encode the file for browser-friendly playback
!ffmpeg -y -i /content/output/smoke_test.mp4 -vcodec libx264 -pix_fmt yuv420p -movflags +faststart /content/output/smoke_test_h264.mp4

from IPython.display import Video
Video("/content/output/smoke_test_h264.mp4", embed=True, width=640)

import cv2, numpy as np

def unit1_edges_corners(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Canny edges
    edges = cv2.Canny(gray, 100, 200)
    edge_col = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)

    # Overlay edges on original
    out = cv2.addWeighted(frame, 0.8, edge_col, 0.5, 0)

    # Corners (Shi–Tomasi)
    pts = cv2.goodFeaturesToTrack(gray, maxCorners=200, qualityLevel=0.01,
                                  minDistance=7, blockSize=7)
    if pts is not None:
        for p in np.int0(pts):
            x, y = p.ravel()
            cv2.circle(out, (x, y), 3, (0,255,0), -1)

    cv2.putText(out, "Unit-1: Canny + Corners",
                (10,25), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)
    return out

from IPython.display import Video

in_path  = "/content/videos/Generating_School_Hallway_Video.mp4"  # or classroom
out_raw  = "/content/output/unit1_edges_corners_raw.mp4"
out_show = "/content/output/unit1_edges_corners.mp4"

cap = cv2.VideoCapture(in_path)
assert cap.isOpened(), "Cannot open input video"
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
FPS = cap.get(cv2.CAP_PROP_FPS) or 30.0
N   = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

writer = cv2.VideoWriter(out_raw, cv2.VideoWriter_fourcc(*'mp4v'), FPS, (W,H))

# process ~10 seconds (adjust if you want)
max_frames = int(min(N, FPS*10))
i = 0
while i < max_frames:
    ok, frame = cap.read()
    if not ok: break
    processed = unit1_edges_corners(frame)
    writer.write(processed)
    i += 1

cap.release()
writer.release()
print(f"wrote {i} frames → {out_raw}")

# Re-encode to H.264 for reliable playback
!ffmpeg -y -loglevel error -i /content/output/unit1_edges_corners_raw.mp4 -vcodec libx264 -pix_fmt yuv420p -movflags +faststart /content/output/unit1_edges_corners.mp4
print("ready:", out_show)

Video(out_show, embed=True, width=640)

import cv2, numpy as np
from skimage.morphology import skeletonize

def unit2_regions_skeleton(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)

    # Binary mask (tweak C and blockSize if needed)
    mask = cv2.adaptiveThreshold(
        blur, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV,
        41, 5
    )

    # Clean small noise
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((3,3), np.uint8), iterations=1)

    # Contours & centroids
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    out = frame.copy()
    for c in cnts:
        if cv2.contourArea(c) < 500:   # ignore tiny blobs
            continue
        x,y,w,h = cv2.boundingRect(c)
        cv2.rectangle(out,(x,y),(x+w,y+h),(255,0,0),2)
        M = cv2.moments(c)
        if M["m00"] != 0:
            cx, cy = int(M["m10"]/M["m00"]), int(M["m01"]/M["m00"])
            cv2.circle(out,(cx,cy),3,(255,0,0),-1)

    # Skeleton (thin the mask)
    skel = skeletonize((mask>0).astype(np.uint8)).astype(np.uint8)*255
    skel_col = cv2.cvtColor(skel, cv2.COLOR_GRAY2BGR)

    # Overlay skeleton
    out = cv2.addWeighted(out, 0.8, skel_col, 0.5, 0)
    cv2.putText(out, "Unit-2: Regions + Skeleton", (10,25),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,0,0), 2)
    return out

from IPython.display import Video

in_path  = "/content/videos/Generating_School_Hallway_Video.mp4"
out_raw  = "/content/output/unit2_regions_skeleton_raw.mp4"
out_show = "/content/output/unit2_regions_skeleton.mp4"

cap = cv2.VideoCapture(in_path)
assert cap.isOpened(), "Cannot open input video"
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
FPS = cap.get(cv2.CAP_PROP_FPS) or 30.0
N   = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

writer = cv2.VideoWriter(out_raw, cv2.VideoWriter_fourcc(*'mp4v'), FPS, (W,H))

max_frames = int(min(N, FPS*10))  # ~10s
i = 0
while i < max_frames:
    ok, frame = cap.read()
    if not ok: break
    processed = unit2_regions_skeleton(frame)
    writer.write(processed)
    i += 1

cap.release()
writer.release()
print(f"wrote {i} frames → {out_raw}")

# Re-encode to H.264 for reliable playback
!ffmpeg -y -loglevel error -i /content/output/unit2_regions_skeleton_raw.mp4 -vcodec libx264 -pix_fmt yuv420p -movflags +faststart /content/output/unit2_regions_skeleton.mp4
print("ready:", out_show)

Video(out_show, embed=True, width=640)

import cv2, numpy as np

def unit3_hough_lines(frame,
                      canny1=80, canny2=160,
                      rho=1, theta=np.pi/180,
                      thresh=70, min_len=60, max_gap=10):
    """Edges → Probabilistic Hough → draw lines."""
    gray  = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blur  = cv2.GaussianBlur(gray, (5,5), 0)
    edges = cv2.Canny(blur, canny1, canny2)

    lines = cv2.HoughLinesP(edges, rho, theta,
                            threshold=thresh,
                            minLineLength=min_len,
                            maxLineGap=max_gap)

    out = frame.copy()
    if lines is not None:
        for (x1,y1,x2,y2) in lines[:,0,:]:
            cv2.line(out, (x1,y1), (x2,y2), (0,255,255), 2)

    cv2.putText(out, "Unit-3: Hough Lines", (10,25),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,255), 2)
    return out

from IPython.display import Video

in_path  = "/content/videos/Driving_and_Walking_Video_Generation.mp4"
out_raw  = "/content/output/unit3_hough_lines_raw.mp4"
out_show = "/content/output/unit3_hough_lines.mp4"

cap = cv2.VideoCapture(in_path)
assert cap.isOpened(), "Cannot open input video"
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
FPS = cap.get(cv2.CAP_PROP_FPS) or 30.0
N   = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

writer = cv2.VideoWriter(out_raw, cv2.VideoWriter_fourcc(*'mp4v'), FPS, (W,H))

max_frames = int(min(N, FPS*10))  # ~10s
i = 0
while i < max_frames:
    ok, frame = cap.read()
    if not ok: break
    processed = unit3_hough_lines(frame)  # you can pass params to tune
    writer.write(processed)
    i += 1

cap.release()
writer.release()
print(f"wrote {i} frames → {out_raw}")

# Re-encode for playback
!ffmpeg -y -loglevel error -i /content/output/unit3_hough_lines_raw.mp4 -vcodec libx264 -pix_fmt yuv420p -movflags +faststart /content/output/unit3_hough_lines.mp4
print("ready:", out_show)

Video(out_show, embed=True, width=640)

import cv2, numpy as np

class OpticalFlowLK:
    def __init__(self,
                 max_corners=300, qlevel=0.01, mindist=7,
                 win=(21,21), max_level=3):
        self.prev_gray = None
        self.prev_pts  = None
        self.params_gftt = dict(maxCorners=max_corners,
                                qualityLevel=qlevel,
                                minDistance=mindist,
                                blockSize=7)
        self.params_lk = dict(winSize=win,
                              maxLevel=max_level,
                              criteria=(cv2.TERM_CRITERIA_EPS |
                                        cv2.TERM_CRITERIA_COUNT, 30, 0.01))
    def reset(self):
        self.prev_gray, self.prev_pts = None, None

    def step(self, frame):
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        vis  = frame.copy()

        # Initialize with corners on first frame (or when we lose many points)
        if self.prev_gray is None or self.prev_pts is None or len(self.prev_pts) < 50:
            self.prev_gray = gray
            self.prev_pts  = cv2.goodFeaturesToTrack(gray, **self.params_gftt)
            cv2.putText(vis, "Unit-4: Optical Flow (init)",
                        (10,25), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,165,255), 2)
            return vis

        next_pts, st, err = cv2.calcOpticalFlowPyrLK(
            self.prev_gray, gray, self.prev_pts, None, **self.params_lk
        )

        if next_pts is not None:
            good_new = next_pts[st==1]
            good_old = self.prev_pts[st==1]

            # Draw motion arrows
            for (x2,y2),(x1,y1) in zip(good_new, good_old):
                x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
                if (x1-x2)**2 + (y1-y2)**2 < 1:  # ignore tiny motion
                    continue
                cv2.arrowedLine(vis, (x1,y1), (x2,y2), (0,165,255), 2, tipLength=0.3)

            # Update state
            self.prev_pts  = good_new.reshape(-1,1,2)
            self.prev_gray = gray

        cv2.putText(vis, "Unit-4: Optical Flow", (10,25),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,165,255), 2)
        return vis

flow = OpticalFlowLK()

from IPython.display import Video

in_path  = "/content/videos/Generating_School_Hallway_Video.mp4"
out_raw  = "/content/output/unit4_optical_flow_raw.mp4"
out_show = "/content/output/unit4_optical_flow.mp4"

cap = cv2.VideoCapture(in_path)
assert cap.isOpened(), "Cannot open input video"
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
FPS = cap.get(cv2.CAP_PROP_FPS) or 30.0
N   = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

writer = cv2.VideoWriter(out_raw, cv2.VideoWriter_fourcc(*'mp4v'), FPS, (W,H))

flow.reset()
max_frames = int(min(N, FPS*10))  # ~10s
i = 0
while i < max_frames:
    ok, frame = cap.read()
    if not ok: break
    vis = flow.step(frame)
    writer.write(vis)
    i += 1

cap.release()
writer.release()
print(f"wrote {i} frames → {out_raw}")

# Re-encode for reliable playback
!ffmpeg -y -loglevel error -i /content/output/unit4_optical_flow_raw.mp4 -vcodec libx264 -pix_fmt yuv420p -movflags +faststart /content/output/unit4_optical_flow.mp4
print("ready:", out_show)

Video(out_show, embed=True, width=640)

import cv2

# Load Haar cascade (ships with OpenCV)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +
                                     "haarcascade_frontalface_default.xml")

def unit5_face_detection(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # tune scaleFactor/minNeighbors if needed
    faces = face_cascade.detectMultiScale(
        gray, scaleFactor=1.2, minNeighbors=5, minSize=(60, 60)
    )
    out = frame.copy()
    for (x,y,w,h) in faces:
        cv2.rectangle(out, (x,y), (x+w, y+h), (0,0,255), 2)
        cv2.putText(out, "Face", (x, y-8), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,0,255), 2)
    cv2.putText(out, "Unit-5: Face Detection", (10,25),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,0,255), 2)
    return out

from IPython.display import Video

in_path  = "/content/videos/College_Students_Candid_Classroom_Video.mp4"
out_raw  = "/content/output/unit5_face_detection_raw.mp4"
out_show = "/content/output/unit5_face_detection.mp4"

cap = cv2.VideoCapture(in_path)
assert cap.isOpened(), "Cannot open input video"
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
FPS = cap.get(cv2.CAP_PROP_FPS) or 30.0
N   = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

writer = cv2.VideoWriter(out_raw, cv2.VideoWriter_fourcc(*'mp4v'), FPS, (W,H))

max_frames = int(min(N, FPS*10))  # ~10s
i = 0
while i < max_frames:
    ok, frame = cap.read()
    if not ok: break
    processed = unit5_face_detection(frame)
    writer.write(processed)
    i += 1

cap.release()
writer.release()
print(f"wrote {i} frames → {out_raw}")

# Re-encode for notebook playback
!ffmpeg -y -loglevel error -i /content/output/unit5_face_detection_raw.mp4 -vcodec libx264 -pix_fmt yuv420p -movflags +faststart /content/output/unit5_face_detection.mp4
print("ready:", out_show)

Video(out_show, embed=True, width=640)

import cv2, os, imutils
from IPython.display import Video

# --- Toggle modules here ---
MODULES = {
    "unit1": True,   # Edges + Corners
    "unit2": True,   # Regions + Skeleton
    "unit3": True,   # Hough Lines
    "unit4": True,   # Optical Flow
    "unit5": True,   # Face Detection
}

# Reuse your optical flow object (created in Step 8); if missing, create one
try:
    flow
except NameError:
    class OpticalFlowLK:
        def __init__(self, max_corners=300, qlevel=0.01, mindist=7, win=(21,21), max_level=3):
            self.prev_gray=None; self.prev_pts=None
            self.params_gftt=dict(maxCorners=max_corners,qualityLevel=qlevel,minDistance=mindist,blockSize=7)
            self.params_lk=dict(winSize=win,maxLevel=max_level,criteria=(cv2.TERM_CRITERIA_EPS|cv2.TERM_CRITERIA_COUNT,30,0.01))
        def reset(self): self.prev_gray=None; self.prev_pts=None
        def step(self, frame):
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            vis  = frame.copy()
            if self.prev_gray is None or self.prev_pts is None or len(self.prev_pts)<50:
                self.prev_gray = gray
                self.prev_pts  = cv2.goodFeaturesToTrack(gray, **self.params_gftt)
                cv2.putText(vis,"Unit-4: Optical Flow (init)",(10,25),cv2.FONT_HERSHEY_SIMPLEX,0.7,(0,165,255),2)
                return vis
            next_pts, st, err = cv2.calcOpticalFlowPyrLK(self.prev_gray, gray, self.prev_pts, None, **self.params_lk)
            if next_pts is not None:
                good_new = next_pts[st==1]; good_old = self.prev_pts[st==1]
                for (x2,y2),(x1,y1) in zip(good_new, good_old):
                    x1,y1,x2,y2 = int(x1),int(y1),int(x2),int(y2)
                    if (x1-x2)**2+(y1-y2)**2 < 1: continue
                    cv2.arrowedLine(vis,(x1,y1),(x2,y2),(0,165,255),2,tipLength=0.3)
                self.prev_pts  = good_new.reshape(-1,1,2)
                self.prev_gray = gray
            cv2.putText(vis,"Unit-4: Optical Flow",(10,25),cv2.FONT_HERSHEY_SIMPLEX,0.7,(0,165,255),2)
            return vis
    flow = OpticalFlowLK()

def apply_pipeline(frame):
    out = frame
    if MODULES.get("unit1"): out = unit1_edges_corners(out)
    if MODULES.get("unit2"): out = unit2_regions_skeleton(out)
    if MODULES.get("unit3"): out = unit3_hough_lines(out)
    if MODULES.get("unit4"): out = flow.step(out)
    if MODULES.get("unit5"): out = unit5_face_detection(out)
    return out

def run_on_video(in_path, out_name="pipeline_output.mp4", resize_width=960, duration_sec=10):
    assert os.path.exists(in_path), f"Input not found: {in_path}"
    cap = cv2.VideoCapture(in_path)
    assert cap.isOpened(), f"Cannot open: {in_path}"
    W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    FPS = cap.get(cv2.CAP_PROP_FPS) or 30.0
    N  = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # For speed, optionally downscale frames (keeps aspect ratio)
    if resize_width and resize_width < W:
        out_w = resize_width
        out_h = int(H * (resize_width / W))
    else:
        out_w, out_h = W, H

    raw_path  = f"/content/output/_raw_{out_name}"
    show_path = f"/content/output/{out_name}"
    writer = cv2.VideoWriter(raw_path, cv2.VideoWriter_fourcc(*'mp4v'), FPS, (out_w, out_h))

    # Reset flow tracker each run
    if MODULES.get("unit4"):
        try: flow.reset()
        except NameError: pass

    max_frames = int(min(N, FPS * duration_sec))
    i = 0
    while i < max_frames:
        ok, frame = cap.read()
        if not ok: break
        if out_w != W:
            frame = imutils.resize(frame, width=out_w)
        processed = apply_pipeline(frame)
        writer.write(processed)
        i += 1
        if i % int(FPS*2) == 0:
            print(f" .. processed {i}/{max_frames} frames")
    cap.release()
    writer.release()
    print(f"✅ wrote {i} frames to {raw_path}")

    # Re-encode for notebook/browser playback
    !ffmpeg -y -loglevel error -i /content/output/_raw_{out_name} -vcodec libx264 -pix_fmt yuv420p -movflags +faststart /content/output/{out_name}
    print("🎬 ready:", show_path)
    return Video(show_path, embed=True, width=640)

def unit1_edges_corners(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Canny edges
    edges = cv2.Canny(gray, 100, 200)
    edge_col = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)
    out = cv2.addWeighted(frame, 0.8, edge_col, 0.5, 0)

    # Good Features to Track (Shi-Tomasi)
    pts = cv2.goodFeaturesToTrack(gray, maxCorners=200, qualityLevel=0.01,
                                  minDistance=7, blockSize=7)
    if pts is not None:
        # ✅ Updated conversion for modern NumPy
        for p in pts.astype(int):
            x, y = p.ravel()
            cv2.circle(out, (x, y), 3, (0, 255, 0), -1)

    cv2.putText(out, "Unit-1: Canny + Corners",
                (10, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
    return out

MODULES.update({"unit1": True, "unit2": True, "unit3": False, "unit4": True, "unit5": False})
run_on_video(
    "/content/videos/Generating_School_Hallway_Video.mp4",
    out_name="demo_hallway_u1_u2_u4_fast.mp4",
    resize_width=720,          # smaller width → faster
    duration_sec=5             # only 5 seconds
)

MODULES.update({"unit1": True, "unit2": False, "unit3": True, "unit4": False, "unit5": False})
run_on_video("/content/videos/Driving_and_Walking_Video_Generation.mp4",
             out_name="demo_driving_u1_u3.mp4", resize_width=960, duration_sec=12)

from google.colab import files, os
for f in os.listdir("/content/output"):
    if f.endswith(".mp4"):
        print("Downloading:", f)
        files.download(f"/content/output/{f}")
